steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ssOleg/test_flask.git']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/PROJECT/test-flask', 'test_flask']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d',  'gcr.io/PROJECT/test-flask']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT/test-flask']
images: ['gcr.io/PROJECT/test-flask']
